/*

EXERCÍCIOS SOBRE PROGRAMAÇÃO ORIENTADA A OBJETOS

EXERCÍCIO 1 - CRIAR UMA ESTRUTURA COM:

     * UMA CLASSE DE MARCA DE CARROS (DE SUA ESCOLHA)
    * UMA SUBCLASSE DE MODELOS DE SUA ESCOLHA
    * ATRIBUTOS DE VIDROS ELÉTRICOS, FREIOS ABS,
    * E TRAÇÃO NAS QUATRO RODAS
    * 
    * METODOS DE ATIVAÇÃO NA TRAÇÃO
    * MUDANÇA DE COMBUSTIVEL (GÁS/GASOLINA - true or false)
    * MÉTODO ATIVAÇÃO DO FREIO ABS
     
    * EXERCÍCIOS 2 - CRIAR UMA ESTRUTURA COM:
    
    *UMA CLASSE DE SHOPPINGS DO RJ (DE SUA ESCOLHA)
    UMA SUBCLASSETIPOS DE LOJAS DE SUA ESCOLHA (por exemplo. "Alimentação", "Vestuário", "Brinquedos")
    * UMA SUBCLASSE DE LOJAS DE SUA ESCOLHA, (por exemplo, "McDonalds's", "Renner", "Rihappy")

    * A SUBSLASSE DE LOJAS TERÁ OS SEGUINTES ATRIBUTOS:
       * Tamanho da loja, Produto Mais Vendido, Aberto24hrs
       * MÉTODO: EXIBIR OS ATRIBUTOS DA LOJA
       */